docker_image(
    name="docker-base-image",
    repository="my-project-base",
    source="Dockerfile",
    context_root="./",
    extra_build_args=["PIP_EXTRA_INDEX_URL"],
    image_tags=["latest"],
)