[GLOBAL]
pants_version = "2.22.0a0"
backend_packages = [
  "pants.backend.docker",
]

[anonymous-telemetry]
enabled = false

[source]
root_patterns = [
  "src/my-project/",
]

[python]
interpreter_constraints = [">=3.9.8,<4"]

[docker]
build_verbose = "True"

[docker.build_args]
PIP_EXTRA_INDEX_URL = "<SOME_URL_HERE>"
